server:
  port: 8098
spring:
  application:
    name: backup
  datasource:
    #mysql
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    #仅仅备份操作，可以是只读账户
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

