server:
  port: 8098
spring:
  application:
    name: dcim-sys
  datasource:
    #mysql
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #clickhouse
    ck:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://127.0.0.1:1234/test?socket_timeout=300000
      usr: root
      password: root
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
      base: test
      cluster: clickhouse_cluster
      selectType: IDC
      task: 0/15 * * * * ?

